url: https://lucasdoreac.github.io/magia-negra-analysis
baseurl: ""
title: Magia Negra e Satanic Panic - Análise Detalhada
description: Uma análise sobre demonização de práticas espirituais e pânicos morais
author: Lucas Dórea Cardoso
safe: true
timezone: UTC